-- Run this file in Supabase SQL Editor after reviewing it.
-- AI outputs are scoped to a group and to the user who uploaded the document.
CREATE TABLE IF NOT EXISTS public.ai_member_profiles (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES public.groups(group_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    profile_json JSONB NOT NULL,
    source_filename TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ai_member_profiles_group_user_unique UNIQUE (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.ai_capstone_projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL UNIQUE REFERENCES public.groups(group_id) ON DELETE CASCADE,
    selected_title TEXT NOT NULL,
    title_details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ai_member_profiles_group_idx
    ON public.ai_member_profiles(group_id);

ALTER TABLE public.ai_member_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_capstone_projects ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ai_member_profiles, public.ai_capstone_projects FROM anon, authenticated;
GRANT ALL ON public.ai_member_profiles, public.ai_capstone_projects TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
