CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_code TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    course TEXT NOT NULL DEFAULT 'Unspecified',
    year_level TEXT NOT NULL DEFAULT '',
    specialty TEXT NOT NULL DEFAULT '',
    skills TEXT[] NOT NULL DEFAULT '{}',
    adviser_id BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL,
    bio TEXT NOT NULL DEFAULT '',
    requirements TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL CHECK (role IN ('student', 'adviser', 'admin', 'superadmin')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.courses (
    course_code TEXT PRIMARY KEY,
    course_name TEXT NOT NULL
);

INSERT INTO public.courses (course_code, course_name)
VALUES ('BSIT', 'BSIT'), ('BSIS', 'BSIS'), ('BSCS', 'BSCS'), ('BSEMC', 'BSEMC')
ON CONFLICT (course_code) DO NOTHING;

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS course TEXT NOT NULL DEFAULT 'Unspecified';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS year_level TEXT NOT NULL DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS specialty TEXT NOT NULL DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS skills TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS adviser_id BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS users_adviser_id_idx ON public.users(adviser_id) WHERE adviser_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.groups (
    group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name TEXT NOT NULL,
    course TEXT NOT NULL,
    specialty TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    owner_id BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'Open' CHECK (status IN ('Open', 'Full')),
    max_members INTEGER NOT NULL DEFAULT 4 CHECK (max_members BETWEEN 2 AND 4),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.group_members (
    group_id BIGINT NOT NULL REFERENCES public.groups(group_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, user_id),
    CONSTRAINT group_members_user_id_unique UNIQUE (user_id)
);

INSERT INTO public.group_members (group_id, user_id)
SELECT group_id, owner_id
FROM public.groups
WHERE owner_id IS NOT NULL
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.group_join_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES public.groups(group_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT group_join_requests_group_user_unique UNIQUE (group_id, user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS group_join_requests_one_pending_per_user
    ON public.group_join_requests(user_id) WHERE status = 'Pending';
CREATE INDEX IF NOT EXISTS groups_created_at_idx ON public.groups(created_at DESC);
CREATE INDEX IF NOT EXISTS group_members_group_id_idx ON public.group_members(group_id);
CREATE INDEX IF NOT EXISTS group_join_requests_group_status_idx ON public.group_join_requests(group_id, status);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_join_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.users, public.groups, public.group_members, public.group_join_requests, public.courses FROM anon, authenticated;
GRANT ALL ON public.users, public.groups, public.group_members, public.group_join_requests, public.courses TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

INSERT INTO public.users (user_code, username, password_hash, name, role)
VALUES
    ('ADMIN-001', 'admin', crypt('admin123', gen_salt('bf')), 'System Admin', 'admin'),
    ('SUPERADMIN-001', 'Superadmin', crypt('superadmin123', gen_salt('bf')), 'Super Admin', 'superadmin'),
    ('2023-00001', 'juan@sti.edu.ph', crypt('juan123', gen_salt('bf')), 'Juan Dela Cruz', 'student'),
    ('ADV-001', 'orbase@sti.edu.ph', crypt('adviser123', gen_salt('bf')), 'Albert Orbase', 'adviser'),
    ('DEMO-STUDENT', 'demo.student', crypt('demo123', gen_salt('bf')), 'Demo Student', 'student'),
    ('DEMO-ADVISER', 'demo.adviser', crypt('demo123', gen_salt('bf')), 'Demo Adviser', 'adviser'),
    ('DEMO-ADMIN', 'demo.admin', crypt('demo123', gen_salt('bf')), 'Demo Admin', 'admin')
ON CONFLICT (username) DO NOTHING;

UPDATE public.users SET course = 'BSIT'
WHERE username IN ('juan@sti.edu.ph', 'demo.student') AND course = 'Unspecified';

CREATE OR REPLACE FUNCTION public.create_group_with_owner(
    p_name TEXT,
    p_course TEXT,
    p_specialty TEXT,
    p_description TEXT,
    p_owner_id BIGINT,
    p_max_members INTEGER
) RETURNS public.groups
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    created_group public.groups;
BEGIN
    IF EXISTS (SELECT 1 FROM public.group_members WHERE user_id = p_owner_id) THEN
        RAISE EXCEPTION 'You can only create or belong to one group.';
    END IF;

    INSERT INTO public.groups (group_name, course, specialty, description, owner_id, max_members)
    VALUES (p_name, p_course, p_specialty, p_description, p_owner_id, p_max_members)
    RETURNING * INTO created_group;

    INSERT INTO public.group_members (group_id, user_id)
    VALUES (created_group.group_id, p_owner_id);
    RETURN created_group;
END;
$$;

DROP FUNCTION IF EXISTS public.request_to_join_group(BIGINT, BIGINT);

CREATE OR REPLACE FUNCTION public.request_to_join_group(p_group_id BIGINT, p_user_id BIGINT, p_allow_superadmin BOOLEAN DEFAULT FALSE)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
    member_count INTEGER;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.users WHERE user_id = p_user_id AND (role = 'student' OR (p_allow_superadmin AND role = 'superadmin')) AND is_active) THEN
        RAISE EXCEPTION 'Only active students can join groups.';
    END IF;
    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF EXISTS (SELECT 1 FROM public.group_members WHERE user_id = p_user_id) THEN
        RAISE EXCEPTION 'You can only belong to one group.';
    END IF;
    IF EXISTS (SELECT 1 FROM public.group_join_requests WHERE user_id = p_user_id AND status = 'Pending') THEN
        RAISE EXCEPTION 'Your join request is still pending.';
    END IF;
    SELECT COUNT(*) INTO member_count FROM public.group_members WHERE group_id = p_group_id;
    IF member_count >= target_group.max_members OR target_group.status = 'Full' THEN
        RAISE EXCEPTION 'This group is full.';
    END IF;
    INSERT INTO public.group_join_requests (group_id, user_id) VALUES (p_group_id, p_user_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.approve_group_request(p_group_id BIGINT, p_request_id BIGINT, p_owner_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
    target_request public.group_join_requests;
    member_count INTEGER;
BEGIN
    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF target_group.owner_id <> p_owner_id THEN RAISE EXCEPTION 'Only the group owner can approve requests.'; END IF;
    SELECT * INTO target_request FROM public.group_join_requests
    WHERE request_id = p_request_id AND group_id = p_group_id AND status = 'Pending' FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Join request not found.'; END IF;
    SELECT COUNT(*) INTO member_count FROM public.group_members WHERE group_id = p_group_id;
    IF member_count >= target_group.max_members THEN RAISE EXCEPTION 'This group is full.'; END IF;
    INSERT INTO public.group_members (group_id, user_id) VALUES (p_group_id, target_request.user_id);
    DELETE FROM public.group_join_requests WHERE request_id = p_request_id;
    UPDATE public.groups SET status = CASE WHEN member_count + 1 >= max_members THEN 'Full' ELSE 'Open' END
    WHERE group_id = p_group_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.add_student_to_group(p_group_id BIGINT, p_student_id BIGINT, p_owner_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
    member_count INTEGER;
BEGIN
    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF target_group.owner_id <> p_owner_id THEN RAISE EXCEPTION 'Only the group owner can manage members.'; END IF;
    IF NOT EXISTS (SELECT 1 FROM public.users WHERE user_id = p_student_id AND role = 'student' AND is_active) THEN
        RAISE EXCEPTION 'Only active students can be added.';
    END IF;
    SELECT COUNT(*) INTO member_count FROM public.group_members WHERE group_id = p_group_id;
    IF member_count >= target_group.max_members THEN RAISE EXCEPTION 'This group is full.'; END IF;
    INSERT INTO public.group_members (group_id, user_id) VALUES (p_group_id, p_student_id);
    UPDATE public.groups SET status = CASE WHEN member_count + 1 >= max_members THEN 'Full' ELSE 'Open' END
    WHERE group_id = p_group_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.create_group_with_owner(TEXT, TEXT, TEXT, TEXT, BIGINT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.request_to_join_group(BIGINT, BIGINT, BOOLEAN) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.approve_group_request(BIGINT, BIGINT, BIGINT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.add_student_to_group(BIGINT, BIGINT, BIGINT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_group_with_owner(TEXT, TEXT, TEXT, TEXT, BIGINT, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.request_to_join_group(BIGINT, BIGINT, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.approve_group_request(BIGINT, BIGINT, BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.add_student_to_group(BIGINT, BIGINT, BIGINT) TO service_role;
