BEGIN;

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS first_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS last_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS birthdate DATE,
    ADD COLUMN IF NOT EXISTS gender TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS socials TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS password_change_required BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE public.users
SET first_name = COALESCE(NULLIF(split_part(btrim(name), ' ', 1), ''), ''),
    last_name = COALESCE(
        NULLIF(btrim(substr(btrim(name), length(split_part(btrim(name), ' ', 1)) + 1)), ''),
        ''
    )
WHERE first_name = '' AND name <> '';

ALTER TABLE public.groups
    ADD COLUMN IF NOT EXISTS finalized_at TIMESTAMPTZ;

ALTER TABLE public.group_join_requests
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

UPDATE public.group_join_requests
SET expires_at = created_at + INTERVAL '24 hours'
WHERE expires_at IS NULL;

ALTER TABLE public.group_join_requests
    ALTER COLUMN expires_at SET DEFAULT (NOW() + INTERVAL '24 hours'),
    ALTER COLUMN expires_at SET NOT NULL;

ALTER TABLE public.group_join_requests
    DROP CONSTRAINT IF EXISTS group_join_requests_status_check;
ALTER TABLE public.group_join_requests
    ADD CONSTRAINT group_join_requests_status_check
    CHECK (status IN ('Pending', 'Approved', 'Declined', 'Expired'));

DROP INDEX IF EXISTS public.group_join_requests_one_pending_per_user;
CREATE UNIQUE INDEX group_join_requests_one_pending_per_user
    ON public.group_join_requests(user_id) WHERE status = 'Pending';
CREATE INDEX IF NOT EXISTS group_join_requests_expires_at_idx
    ON public.group_join_requests(expires_at) WHERE status = 'Pending';

CREATE TABLE IF NOT EXISTS public.portfolio_entries (
    portfolio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    course TEXT NOT NULL DEFAULT 'Unspecified',
    project_title TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Other',
    description TEXT NOT NULL DEFAULT '',
    file_name TEXT NOT NULL,
    storage_path TEXT NOT NULL UNIQUE,
    file_type TEXT NOT NULL,
    file_size BIGINT NOT NULL CHECK (file_size > 0 AND file_size <= 10485760),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS portfolio_entries_user_created_idx
    ON public.portfolio_entries(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS portfolio_entries_course_idx
    ON public.portfolio_entries(course);

CREATE TABLE IF NOT EXISTS public.auth_sessions (
    session_hash TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS auth_sessions_expires_at_idx ON public.auth_sessions(expires_at);

CREATE TABLE IF NOT EXISTS public.group_membership_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    admin_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE RESTRICT,
    action TEXT NOT NULL CHECK (action IN ('add', 'remove')),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS group_membership_audit_group_idx
    ON public.group_membership_audit(group_id, changed_at DESC);

CREATE TABLE IF NOT EXISTS public.temporary_accounts (
    temporary_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL,
    email TEXT,
    role TEXT NOT NULL CHECK (role IN ('student', 'adviser')),
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
    status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Used', 'Expired', 'Revoked')),
    used_at TIMESTAMPTZ,
    CONSTRAINT temporary_accounts_identity_check CHECK (user_id IS NOT NULL OR email IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS temporary_accounts_expiration_idx
    ON public.temporary_accounts(expires_at) WHERE status = 'Pending';

CREATE OR REPLACE FUNCTION public.issue_temporary_account(
    p_user_id BIGINT,
    p_password_hash TEXT,
    p_expires_at TIMESTAMPTZ
) RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_user public.users;
BEGIN
    SELECT * INTO target_user FROM public.users WHERE user_id = p_user_id FOR UPDATE;
    IF NOT FOUND OR target_user.role NOT IN ('student', 'adviser') THEN
        RAISE EXCEPTION 'Only student or adviser accounts may receive temporary access.';
    END IF;
    UPDATE public.temporary_accounts SET status = 'Revoked'
    WHERE user_id = p_user_id AND status = 'Pending';
    INSERT INTO public.temporary_accounts (user_id, email, role, password_hash, expires_at)
    VALUES (p_user_id, target_user.username, target_user.role, p_password_hash, p_expires_at);
    DELETE FROM public.auth_sessions WHERE user_id = p_user_id;
    UPDATE public.users SET password_hash = p_password_hash, password_change_required = TRUE,
        expires_at = p_expires_at, is_active = TRUE
    WHERE user_id = p_user_id;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.issue_temporary_account(BIGINT, TEXT, TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.issue_temporary_account(BIGINT, TEXT, TIMESTAMPTZ) TO service_role;

CREATE OR REPLACE FUNCTION public.complete_temporary_account(p_user_id BIGINT, p_password_hash TEXT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    UPDATE public.users SET password_hash = p_password_hash, password_change_required = FALSE
    WHERE user_id = p_user_id AND password_change_required = TRUE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Temporary password change is no longer required.'; END IF;
    UPDATE public.temporary_accounts SET status = 'Used', used_at = NOW()
    WHERE user_id = p_user_id AND status = 'Pending';
END;
$$;
REVOKE EXECUTE ON FUNCTION public.complete_temporary_account(BIGINT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.complete_temporary_account(BIGINT, TEXT) TO service_role;

ALTER TABLE public.portfolio_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auth_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.temporary_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_membership_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.auth_sessions, public.portfolio_entries, public.temporary_accounts, public.group_membership_audit FROM anon, authenticated;
GRANT ALL ON public.auth_sessions, public.portfolio_entries, public.temporary_accounts, public.group_membership_audit TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.portfolio_entries_portfolio_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.temporary_accounts_temporary_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.group_membership_audit_audit_id_seq TO service_role;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'student-portfolios',
    'student-portfolios',
    FALSE,
    10485760,
    ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'text/plain',
          'application/msword',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
)
ON CONFLICT (id) DO UPDATE
SET public = FALSE,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE OR REPLACE FUNCTION public.create_group_with_owner(
    p_name TEXT,
    p_course TEXT,
    p_specialty TEXT,
    p_description TEXT,
    p_owner_id BIGINT,
    p_max_members INTEGER
) RETURNS public.groups
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    created_group public.groups;
BEGIN
    IF p_max_members < 2 OR p_max_members > 4 THEN
        RAISE EXCEPTION 'Group size must be between 2 and 4.';
    END IF;
    IF EXISTS (SELECT 1 FROM public.group_members WHERE user_id = p_owner_id) THEN
        RAISE EXCEPTION 'You can only create or belong to one group.';
    END IF;

    INSERT INTO public.groups (group_name, course, specialty, description, owner_id, max_members)
    VALUES (p_name, p_course, p_specialty, p_description, p_owner_id, p_max_members)
    RETURNING * INTO created_group;

    INSERT INTO public.group_members (group_id, user_id)
    VALUES (created_group.group_id, p_owner_id);
    RETURN created_group;
END;
$$;

CREATE OR REPLACE FUNCTION public.request_to_join_group(
    p_group_id BIGINT,
    p_user_id BIGINT,
    p_allow_superadmin BOOLEAN DEFAULT FALSE
) RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
    member_count INTEGER;
BEGIN
    UPDATE public.group_join_requests
    SET status = 'Expired'
    WHERE user_id = p_user_id AND status = 'Pending' AND expires_at <= NOW();

    IF NOT EXISTS (
        SELECT 1 FROM public.users
        WHERE user_id = p_user_id
          AND (role = 'student' OR (p_allow_superadmin AND role = 'superadmin'))
          AND is_active AND (expires_at IS NULL OR expires_at > NOW())
    ) THEN
        RAISE EXCEPTION 'Only active students can join groups.';
    END IF;

    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF target_group.finalized_at IS NOT NULL THEN RAISE EXCEPTION 'This group is finalized.'; END IF;
    IF EXISTS (SELECT 1 FROM public.group_members WHERE user_id = p_user_id) THEN
        RAISE EXCEPTION 'You can only belong to one group.';
    END IF;
    IF EXISTS (
        SELECT 1 FROM public.group_join_requests
        WHERE user_id = p_user_id AND status = 'Pending' AND expires_at > NOW()
    ) THEN
        RAISE EXCEPTION 'Your join request is still pending.';
    END IF;

    SELECT COUNT(*) INTO member_count FROM public.group_members WHERE group_id = p_group_id;
    IF member_count >= target_group.max_members OR target_group.status = 'Full' THEN
        UPDATE public.group_join_requests
        SET status = 'Expired'
        WHERE group_id = p_group_id AND status = 'Pending';
        RAISE EXCEPTION 'This group is full.';
    END IF;
    INSERT INTO public.group_join_requests (group_id, user_id) VALUES (p_group_id, p_user_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.approve_group_request(
    p_group_id BIGINT,
    p_request_id BIGINT,
    p_owner_id BIGINT
) RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
    target_request public.group_join_requests;
    member_count INTEGER;
BEGIN
    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF target_group.owner_id <> p_owner_id THEN RAISE EXCEPTION 'Only the group owner can approve requests.'; END IF;
    IF target_group.finalized_at IS NOT NULL THEN RAISE EXCEPTION 'This group is finalized.'; END IF;

    UPDATE public.group_join_requests
    SET status = 'Expired'
    WHERE group_id = p_group_id AND status = 'Pending' AND expires_at <= NOW();
    SELECT * INTO target_request FROM public.group_join_requests
    WHERE request_id = p_request_id AND group_id = p_group_id
      AND status = 'Pending' AND expires_at > NOW()
    FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Join request not found or expired.'; END IF;

    SELECT COUNT(*) INTO member_count FROM public.group_members WHERE group_id = p_group_id;
    IF member_count >= target_group.max_members THEN
        UPDATE public.group_join_requests SET status = 'Expired'
        WHERE group_id = p_group_id AND status = 'Pending';
        UPDATE public.groups SET status = 'Full' WHERE group_id = p_group_id;
        RAISE EXCEPTION 'This group is full.';
    END IF;

    INSERT INTO public.group_members (group_id, user_id) VALUES (p_group_id, target_request.user_id);
    UPDATE public.group_join_requests SET status = 'Approved' WHERE request_id = p_request_id;
    UPDATE public.groups
    SET status = CASE WHEN member_count + 1 >= max_members THEN 'Full' ELSE 'Open' END
    WHERE group_id = p_group_id;
    IF member_count + 1 >= target_group.max_members THEN
        UPDATE public.group_join_requests SET status = 'Expired'
        WHERE group_id = p_group_id AND status = 'Pending';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.add_student_to_group(
    p_group_id BIGINT,
    p_student_id BIGINT,
    p_owner_id BIGINT
) RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
    member_count INTEGER;
BEGIN
    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF target_group.owner_id <> p_owner_id THEN RAISE EXCEPTION 'Only the group owner can manage members.'; END IF;
    IF target_group.finalized_at IS NOT NULL THEN RAISE EXCEPTION 'This group is finalized.'; END IF;
    IF NOT EXISTS (SELECT 1 FROM public.users WHERE user_id = p_student_id AND role = 'student' AND is_active) THEN
        RAISE EXCEPTION 'Only active students can be added.';
    END IF;

    SELECT COUNT(*) INTO member_count FROM public.group_members WHERE group_id = p_group_id;
    IF member_count >= target_group.max_members THEN RAISE EXCEPTION 'This group is full.'; END IF;
    INSERT INTO public.group_members (group_id, user_id) VALUES (p_group_id, p_student_id);
    UPDATE public.groups
    SET status = CASE WHEN member_count + 1 >= max_members THEN 'Full' ELSE 'Open' END
    WHERE group_id = p_group_id;
    IF member_count + 1 >= target_group.max_members THEN
        UPDATE public.group_join_requests SET status = 'Expired'
        WHERE group_id = p_group_id AND status = 'Pending';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.finalize_group(p_group_id BIGINT, p_owner_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
BEGIN
    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF target_group.owner_id <> p_owner_id THEN RAISE EXCEPTION 'Only the group owner can finalize this group.'; END IF;
    IF target_group.finalized_at IS NOT NULL THEN RETURN; END IF;
    UPDATE public.groups SET finalized_at = NOW() WHERE group_id = p_group_id;
    UPDATE public.group_join_requests SET status = 'Expired'
    WHERE group_id = p_group_id AND status = 'Pending';
END;
$$;

CREATE OR REPLACE FUNCTION public.update_owned_group(
    p_group_id BIGINT,
    p_owner_id BIGINT,
    p_name TEXT,
    p_description TEXT,
    p_specialty TEXT,
    p_max_members INTEGER
) RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
    member_count INTEGER;
BEGIN
    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF target_group.owner_id <> p_owner_id THEN RAISE EXCEPTION 'Only the group owner can manage members.'; END IF;
    IF target_group.finalized_at IS NOT NULL THEN RAISE EXCEPTION 'This group is finalized.'; END IF;
    IF p_max_members < 2 OR p_max_members > 4 OR NOT p_name ~ '\S' THEN
        RAISE EXCEPTION 'Group details are invalid.';
    END IF;
    SELECT COUNT(*) INTO member_count FROM public.group_members WHERE group_id = p_group_id;
    IF p_max_members < member_count THEN RAISE EXCEPTION 'Maximum size cannot be below the current member count.'; END IF;
    UPDATE public.groups
    SET group_name = trim(p_name), description = trim(p_description),
        specialty = trim(p_specialty), max_members = p_max_members,
        status = CASE WHEN member_count >= p_max_members THEN 'Full' ELSE 'Open' END
    WHERE group_id = p_group_id;
    IF member_count >= p_max_members THEN
        UPDATE public.group_join_requests SET status = 'Expired'
        WHERE group_id = p_group_id AND status = 'Pending';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_owned_group(p_group_id BIGINT, p_owner_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
BEGIN
    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF target_group.owner_id <> p_owner_id THEN RAISE EXCEPTION 'Only the group owner can delete this group.'; END IF;
    IF target_group.finalized_at IS NOT NULL THEN RAISE EXCEPTION 'Finalized groups cannot be deleted by students.'; END IF;
    DELETE FROM public.groups WHERE group_id = p_group_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.remove_student_from_group(
    p_group_id BIGINT,
    p_student_id BIGINT,
    p_owner_id BIGINT
) RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
BEGIN
    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF target_group.owner_id <> p_owner_id THEN RAISE EXCEPTION 'Only the group owner can manage members.'; END IF;
    IF target_group.finalized_at IS NOT NULL THEN RAISE EXCEPTION 'This group is finalized.'; END IF;
    IF p_student_id = target_group.owner_id THEN RAISE EXCEPTION 'The group leader cannot be removed.'; END IF;
    DELETE FROM public.group_members WHERE group_id = p_group_id AND user_id = p_student_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Student is not in this group.'; END IF;
    UPDATE public.groups SET status = 'Open' WHERE group_id = p_group_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_change_finalized_group_member(
    p_group_id BIGINT,
    p_student_id BIGINT,
    p_admin_id BIGINT,
    p_action TEXT
) RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    target_group public.groups;
    member_count INTEGER;
BEGIN
    IF p_action NOT IN ('add', 'remove') THEN RAISE EXCEPTION 'Membership action is invalid.'; END IF;
    IF NOT EXISTS (SELECT 1 FROM public.users WHERE user_id = p_admin_id AND role IN ('admin', 'superadmin') AND is_active) THEN
        RAISE EXCEPTION 'Admin access is required.';
    END IF;
    SELECT * INTO target_group FROM public.groups WHERE group_id = p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Group not found.'; END IF;
    IF target_group.finalized_at IS NULL THEN RAISE EXCEPTION 'Administrative override is only for finalized groups.'; END IF;
    IF NOT EXISTS (
        SELECT 1 FROM public.users
        WHERE user_id = p_student_id AND role = 'student' AND is_active
          AND (expires_at IS NULL OR expires_at > NOW())
    ) THEN
        RAISE EXCEPTION 'Only active student accounts may be group members.';
    END IF;
    IF p_action = 'add' AND EXISTS (SELECT 1 FROM public.group_members WHERE user_id = p_student_id) THEN
        RAISE EXCEPTION 'Student already belongs to a group.';
    END IF;

    SELECT COUNT(*) INTO member_count FROM public.group_members WHERE group_id = p_group_id;
    IF p_action = 'add' THEN
        IF member_count >= target_group.max_members THEN RAISE EXCEPTION 'This group is full.'; END IF;
        INSERT INTO public.group_members (group_id, user_id) VALUES (p_group_id, p_student_id);
    ELSE
        IF p_student_id = target_group.owner_id THEN RAISE EXCEPTION 'The group leader cannot be removed.'; END IF;
        DELETE FROM public.group_members WHERE group_id = p_group_id AND user_id = p_student_id;
        IF NOT FOUND THEN RAISE EXCEPTION 'Student is not in this group.'; END IF;
    END IF;

    INSERT INTO public.group_membership_audit (group_id, user_id, admin_id, action)
    VALUES (p_group_id, p_student_id, p_admin_id, p_action);
    SELECT COUNT(*) INTO member_count FROM public.group_members WHERE group_id = p_group_id;
    UPDATE public.groups SET status = CASE WHEN member_count >= max_members THEN 'Full' ELSE 'Open' END
    WHERE group_id = p_group_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.create_group_with_owner(TEXT, TEXT, TEXT, TEXT, BIGINT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.request_to_join_group(BIGINT, BIGINT, BOOLEAN) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.approve_group_request(BIGINT, BIGINT, BIGINT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.add_student_to_group(BIGINT, BIGINT, BIGINT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.finalize_group(BIGINT, BIGINT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_owned_group(BIGINT, BIGINT, TEXT, TEXT, TEXT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.delete_owned_group(BIGINT, BIGINT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.remove_student_from_group(BIGINT, BIGINT, BIGINT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_change_finalized_group_member(BIGINT, BIGINT, BIGINT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_group_with_owner(TEXT, TEXT, TEXT, TEXT, BIGINT, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.request_to_join_group(BIGINT, BIGINT, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.approve_group_request(BIGINT, BIGINT, BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.add_student_to_group(BIGINT, BIGINT, BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.finalize_group(BIGINT, BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_owned_group(BIGINT, BIGINT, TEXT, TEXT, TEXT, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.delete_owned_group(BIGINT, BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.remove_student_from_group(BIGINT, BIGINT, BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_change_finalized_group_member(BIGINT, BIGINT, BIGINT, TEXT) TO service_role;

CREATE OR REPLACE FUNCTION public.expire_juan_finder_records()
RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    UPDATE public.group_join_requests
    SET status = 'Expired'
    WHERE status = 'Pending' AND expires_at <= NOW();
    DELETE FROM public.auth_sessions
    WHERE user_id IN (
        SELECT user_id FROM public.users
        WHERE is_active AND expires_at IS NOT NULL AND expires_at <= NOW()
    );
    UPDATE public.users SET is_active = FALSE
    WHERE is_active AND expires_at IS NOT NULL AND expires_at <= NOW();
    UPDATE public.temporary_accounts SET status = 'Expired'
    WHERE status = 'Pending' AND expires_at <= NOW();
END;
$$;
REVOKE EXECUTE ON FUNCTION public.expire_juan_finder_records() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.expire_juan_finder_records() TO service_role;

DO $$
DECLARE
    existing_job BIGINT;
BEGIN
    EXECUTE 'CREATE EXTENSION IF NOT EXISTS pg_cron';
    SELECT jobid INTO existing_job FROM cron.job WHERE jobname = 'juan-finder-expire-records';
    IF existing_job IS NOT NULL THEN
        PERFORM cron.unschedule(existing_job);
    END IF;
    PERFORM cron.schedule(
        'juan-finder-expire-records',
        '*/5 * * * *',
        'SELECT public.expire_juan_finder_records()'
    );
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'pg_cron scheduling unavailable; call public.expire_juan_finder_records() from a Supabase scheduled job.';
END
$$;

COMMIT;
